# Generated by Django 6.0.7 on 2026-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('strength', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('input_price_per_1k_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('output_price_per_1k_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
