# Generated by Django 6.0.7 on 2026-08-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_llm_model'),
        ),
    ]
