# Generated by Django 6.0.7 on 2026-08-06 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents_processing.processeddocument')),
            ],
            options={
                'ordering': ['chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('processed_document', 'chunk_index'), name='unique_document_chunk_index')],
            },
        ),
    ]
