# Generated by Django 6.0.7 on 2026-08-07 01:34

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_processing', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='documents_processing.documentchunk')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chunk', 'provider', 'model_name'), name='unique_chunk_embedding_model')],
            },
        ),
    ]
